Repository micronaut-projects/micronaut-sql, pull requests merged in 2020-07, with the labels that each got.

#230 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#240 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#238 [sql] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#239 [sql] Update common files for branch 1.4.x
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#241 [sql] Update common files for branch master
  .github/workflows/dependency-check.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#242 [sql] Update common files for branch 1.4.x
  .github/workflows/dependency-check.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#244 [sql] Update common files for branch master
  .github/dependabot.yml
  .github/workflows/dependency-update.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#245 [sql] Update common files for branch 1.4.x
  .github/dependabot.yml
  .github/workflows/dependency-update.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#246 [sql] Update common files for branch master
  .github/settings.yml
  .github/workflows/label-sync.yml
  .github/workflows/release.yml
Labels: relates-to: build

#248 Dependency upgrades
  vertx-mysql-client/build.gradle
Labels: type: dependency-upgrade

#249 [sql] Update common files for branch 1.4.x
  .github/workflows/label-sync.yml
  .github/workflows/release.yml
Labels: relates-to: build

#251 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#259 Remove Probot settings file
  .github/settings.yml
Labels: relates-to: build

#265 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#266 Jasync configure interceptors
  jasync-sql/src/main/java/io/micronaut/configuration/jasync/JasyncPoolConfiguration.java
  jasync-sql/src/test/groovy/io/micronaut/configuration/jasync/ApplicationContextSpecification.groovy
  jasync-sql/src/test/groovy/io/micronaut/configuration/jasync/ConfigurationFixture.groovy
  jasync-sql/src/test/groovy/io/micronaut/configuration/jasync/JasyncConfigurationSpec.groovy
  jasync-sql/src/test/groovy/io/micronaut/configuration/jasync/JasyncQueryInterceptorsSpec.groovy
  src/main/docs/guide/jasync.adoc
Labels: type: improvement

#272 build: don't qualify micronaut-spring
  hibernate-jpa-spring/build.gradle
Labels: relates-to: build
