Repository micronaut-projects/micronaut-sql, pull requests merged in 2020-08, with the labels that each got.

#280 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#281 Dependency upgrades
  jdbi/build.gradle
Labels: type: dependency-upgrade

#279 Hibernate JPA support for additional XML mapping resources
  hibernate-jpa/src/main/java/io/micronaut/configuration/hibernate/jpa/EntityManagerFactoryBean.java
  hibernate-jpa/src/main/java/io/micronaut/configuration/hibernate/jpa/JpaConfiguration.java
  hibernate-jpa/src/test/groovy/io/micronaut/configuration/hibernate/jpa/JpaConfigurationSpec.groovy
  hibernate-jpa/src/test/groovy/io/micronaut/configuration/hibernate/jpa/mapping/Account.java
  hibernate-jpa/src/test/groovy/io/micronaut/configuration/hibernate/jpa/mapping/AccountRepository.java
  hibernate-jpa/src/test/groovy/io/micronaut/configuration/hibernate/jpa/mapping/CustomIndexesDatabaseObject.java
  hibernate-jpa/src/test/groovy/io/micronaut/configuration/hibernate/jpa/mapping/MappingResourcesSpec.groovy
  hibernate-jpa/src/test/resources/hibernate/custom.hbm.xml
Labels: type: enhancement

#285 [sql] Update common files for branch 1.4.x
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#284 [sql] Update common files for branch master
  README.md
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#291 Dependency upgrades
  jdbi/build.gradle
Labels: type: dependency-upgrade

#290 [sql] Update common files for branch 1.4.x
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: relates-to: build

#289 [sql] Update common files for branch master
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: relates-to: build

#294 Dependency upgrades
  build.gradle
Labels: type: dependency-upgrade

#296 [sql] Update common files for branch master
  .github/workflows/release-notes.yml
Labels: relates-to: build

#297 [sql] Update common files for branch 1.4.x
  .github/workflows/release-notes.yml
Labels: relates-to: build

#298 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade
