Repository micronaut-projects/micronaut-sql, pull requests merged in 2022-07, with the labels that each got.

#684 Duplicate managed-commons-dbcp depenedency for core compatibility
  gradle/libs.versions.toml
Labels: relates-to: build

#697 build: Stop publishing jooq as a Java 11 jar
  jooq/build.gradle
Labels: relates-to: build, type: bug

#704 Remove Oracle JDBC native image configuration
  jdbc/src/main/java/io/micronaut/jdbc/nativeimage/JdbcFeature.java
Labels: relates-to: graal, type: bug

#702 bug: SqlServerDriverStringProperty is initialized at build time
  jdbc/src/main/java/io/micronaut/jdbc/nativeimage/JdbcFeature.java
Labels: relates-to: graal, type: bug
