Repository micronaut-projects/micronaut-sql, pull requests merged in 2023-05, with the labels that each got.

#861 [sql] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/graalvm.yml
  buildSrc/src/main/groovy/io.micronaut.build.internal.test-application.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.test-library.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  tests/common/build.gradle
  tests/hibernate6/hibernate6-h2/build.gradle
Labels: relates-to: build

#880 data M3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#890 Check if Metrics are enabled prior to getting the MeterRegistry bean
  jdbc-hikari/src/main/java/io/micronaut/configuration/jdbc/hikari/DatasourceFactory.java
  settings.gradle
Labels: type: bug

#864 Make jakarta tx and persistence managed
  gradle/libs.versions.toml
  hibernate-jpa/build.gradle
  jooq/build.gradle
Labels: type: improvement

#891 Micronaut Framework 4.0.0-M4
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.sql-base.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.test-application.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.test-library.gradle
  config/accepted-api-changes.json
  gradle.properties
  gradle/libs.versions.toml
  hibernate-jpa/build.gradle
  jdbi/build.gradle
  settings.gradle
  tests/hibernate6/hibernate6-reactive-common/build.gradle
  tests/hibernate6/hibernate6-sync-common/build.gradle
  tests/jooq-tests/jooq-jdbc-postgres/build.gradle
  tests/jooq-tests/jooq-r2dbc-postgres/build.gradle
Labels: type: dependency-upgrade

#894 [sql] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#908 [sql] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
Labels: relates-to: build
