Repository micronaut-projects/micronaut-sql, pull requests merged in 2023-07, with the labels that each got.

#1007 [sql] Update common files for branch master
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#1013 SQL to Core 4.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#881 Disable JPA via configuration
  hibernate-jpa/src/main/java/io/micronaut/configuration/hibernate/jpa/package-info.java
  settings.gradle
  src/main/docs/guide/hibernate/hibernate-disable.adoc
  src/main/docs/guide/toc.yml
  tests/hibernate6/hibernate6-mysql-disabled/build.gradle
  tests/hibernate6/hibernate6-mysql-disabled/src/main/resources/application.properties
  tests/hibernate6/hibernate6-mysql-disabled/src/test/java/example/hibernate6/sync/TempTest.java
  tests/hibernate6/hibernate6-mysql-disabled/src/test/resources/logback.xml
Labels: type: improvement

#1029 [sql] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#1035 [sql] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#1039 [sql] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build
